import type { ThemeConfig, ThemeId } from './types';

export const themes: Record<ThemeId, ThemeConfig> = {
  dark: {
    id: 'dark',
    name: '暗夜黑',
    description: '经典深色主题',
    colors: {
      primary: '#000000',
      primaryLight: 'rgba(0, 0, 0, 0.3)',
      background: '#0f0f0f',
      sidebar: '#161616',
      card: '#1a1a1a',
      cardAccent: '#3a3a3a',
      cardDim: '#101010',
      hover: '#252525',
      text: '#ffffff',
      foreground: '#ffffff',
      mutedForeground: '#a0a0a0',
      disabledForeground: '#666666',
      success: '#22c55e',
      warning: '#eab308',
      error: '#ef4444',
      favorite: '#e91e63',
      border: '#2a2a2a',
      borderHighlight: 'rgba(0, 0, 0, 0.6)',
      popover: '#1a1a1a',
      secondary: '#2a2a2a',
      secondaryForeground: '#fafafa',
      accent: '#2a2a2a',
      destructive: '#ef4444',
      input: '#2a2a2a',
      ring: '#000000',
      surface: '#1f1f1f',
      surfaceElevated: '#111111',
      textSecondary: '#e0e0e0',
      trackBg: '#2a2a2a',
      buttonPrimaryText: '#ffffff',
      buttonSecondaryText: '#fafafa',
      buttonDestructiveText: '#ef4444',
      swiftTrack: '#333333',
      swiftActiveTrack: '#22c55e',
      swiftThumb: '#ffffff',
    },
  },
  light: {
    id: 'light',
    name: '晨曦白',
    description: '清爽浅色主题',
    colors: {
      primary: '#ffffff',
      primaryLight: 'rgba(255, 255, 255, 0.3)',
      background: '#f8fafc',
      sidebar: '#ffffff',
      card: '#ffffff',
      cardAccent: '#dcdddf',
      cardDim: '#bdc0c4',
      hover: '#f1f5f9',
      text: '#000000',
      foreground: '#000000',
      mutedForeground: '#333333',
      disabledForeground: '#555555',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      favorite: '#ec4899',
      border: '#e2e8f0',
      borderHighlight: 'rgba(255, 255, 255, 0.6)',
      popover: '#ffffff',
      secondary: '#f1f5f9',
      secondaryForeground: '#000000',
      accent: '#f1f5f9',
      destructive: '#ef4444',
      input: '#e2e8f0',
      ring: '#ffffff',
      surface: '#f1f5f9',
      surfaceElevated: '#ffffff',
      trackBg: '#e2e8f0',
      textSecondary: '#1a1a1a',
      buttonPrimaryText: '#000000',
      buttonSecondaryText: '#1a1a1a',
      buttonDestructiveText: '#ffffff',
      swiftTrack: '#cbd5e1',
      swiftActiveTrack: '#22c55e',
      swiftThumb: '#000000',
    },
  },
};

export const DEFAULT_THEME: ThemeId = 'dark';
export const THEME_KEY = 'movie-app-theme';